
server:
    port: 8085
spring:
  application:
    name: CONFIG-SERVER

#create a git repository and add the following files
#this is a cloud config server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Daniel-LA0303/mcsv_spring_config
          clone-on-start: true


